Import of m4-1.4ppre2

diff --git a/modules/Makefile.in b/modules/Makefile.in
--- a/modules/Makefile.in
+++ b/modules/Makefile.in
@@ -10,10 +10,6 @@
 # even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 # PARTICULAR PURPOSE.
 
-# To get libtool and Automake to handle this correctly it is necessary
-# to pretend we are compiling shared libraries (which we are) and then
-# change the names when installing.
-
 
 SHELL = @SHELL@
 
@@ -72,6 +68,7 @@ CPP = @CPP@
 DATADIRNAME = @DATADIRNAME@
 DLLDFLAGS = @DLLDFLAGS@
 DLLTOOL = @DLLTOOL@
+EXEEXT = @EXEEXT@
 GENCAT = @GENCAT@
 GMOFILES = @GMOFILES@
 GMSGFMT = @GMSGFMT@
@@ -84,8 +81,12 @@ INTLINCL = @INTLINCL@
 INTLLIBS = @INTLLIBS@
 INTLOBJS = @INTLOBJS@
 LD = @LD@
+LIBADD_DL = @LIBADD_DL@
+LIBM4_DLL_IMPORT = @LIBM4_DLL_IMPORT@
 LIBTOOL = @LIBTOOL@
 LN_S = @LN_S@
+LTLIBOBJS = @LTLIBOBJS@
+M4OBJS = @M4OBJS@
 MAKEINFO = @MAKEINFO@
 MKINSTALLDIRS = @MKINSTALLDIRS@
 MODULES_DIR = @MODULES_DIR@
@@ -108,28 +109,29 @@ pkglibexecdir = @pkglibexecdir@
 
 MAINTAINERCLEANFILES = Makefile.in
 
-pkglibexec_LTLIBRARIES = test.la time.la stdlib.la
+pkglibexec_LTLIBRARIES = test.la shadow.la time.la stdlib.la
 
-EXTRA_DIST = test.m4 time.m4 stdlib.m4
+EXTRA_DIST = test.m4 shadow.m4 time.m4 time2.m4 stdlib.m4 	 $(TESTS) defs
 
-INCLUDES = -I$(srcdir)/../src -I$(srcdir)/../lib @INTLINCL@
+
+TESTS = test.test time.test shadow.test 	modpath1.test modpath2.test modpath3.test modpath4.test
+
+
+AM_CPPFLAGS = @LIBM4_DLL_IMPORT@
+INCLUDES = -I$(top_srcdir)/src -I$(top_srcdir)/lib -I$(top_srcdir)/libltdl -I/usr/local/include @INTLINCL@
 
 test_la_SOURCES = test.c
+shadow_la_SOURCES = shadow.c
 time_la_SOURCES = time.c
 stdlib_la_SOURCES = stdlib.c
 
-test_la_LDFLAGS = -module
-time_la_LDFLAGS = -module
-stdlib_la_LDFLAGS = -module
-
-LIBS = 
+LIBS = $(top_srcdir)/lib/libm4.la
 LDFLAGS = -no-undefined -module -avoid-version @DLLDFLAGS@
 
-# libperl_la_SOURCES = perl.c perlxsi.c
-libperl_la_OBJECTS = perl.lo
-
-libperl_la_CFLAGS = `perl -MExtUtils::Embed -e ccopts`
-PERLLDFLAGS = `perl -MExtUtils::Embed -e ldopts`
+test_la_LDFLAGS = -module
+shadow_la_LDFLAGS = -module
+time_la_LDFLAGS = -module
+stdlib_la_LDFLAGS = -module
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
 CONFIG_HEADER = ../config.h
 CONFIG_CLEAN_FILES = 
@@ -140,6 +142,8 @@ DEFS = @DEFS@ -I. -I$(srcdir) -I..
 CPPFLAGS = @CPPFLAGS@
 test_la_LIBADD = 
 test_la_OBJECTS =  test.lo
+shadow_la_LIBADD = 
+shadow_la_OBJECTS =  shadow.lo
 time_la_LIBADD = 
 time_la_OBJECTS =  time.lo
 stdlib_la_LIBADD = 
@@ -149,15 +153,15 @@ COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CF
 LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
 CCLD = $(CC)
 LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
-DIST_COMMON =  README Makefile.am Makefile.in TODO
+DIST_COMMON =  README Makefile.am Makefile.in
 
 
 DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)
 
 TAR = tar
 GZIP_ENV = --best
-SOURCES = $(test_la_SOURCES) $(time_la_SOURCES) $(stdlib_la_SOURCES)
-OBJECTS = $(test_la_OBJECTS) $(time_la_OBJECTS) $(stdlib_la_OBJECTS)
+SOURCES = $(test_la_SOURCES) $(shadow_la_SOURCES) $(time_la_SOURCES) $(stdlib_la_SOURCES)
+OBJECTS = $(test_la_OBJECTS) $(shadow_la_OBJECTS) $(time_la_OBJECTS) $(stdlib_la_OBJECTS)
 
 all: all-redirect
 .SUFFIXES:
@@ -236,6 +240,9 @@ maintainer-clean-libtool:
 test.la: $(test_la_OBJECTS) $(test_la_DEPENDENCIES)
 	$(LINK) -rpath $(pkglibexecdir) $(test_la_LDFLAGS) $(test_la_OBJECTS) $(test_la_LIBADD) $(LIBS)
 
+shadow.la: $(shadow_la_OBJECTS) $(shadow_la_DEPENDENCIES)
+	$(LINK) -rpath $(pkglibexecdir) $(shadow_la_LDFLAGS) $(shadow_la_OBJECTS) $(shadow_la_LIBADD) $(LIBS)
+
 time.la: $(time_la_OBJECTS) $(time_la_DEPENDENCIES)
 	$(LINK) -rpath $(pkglibexecdir) $(time_la_LDFLAGS) $(time_la_OBJECTS) $(time_la_LIBADD) $(LIBS)
 
@@ -286,12 +293,48 @@ distdir: $(DISTFILES)
 	    || cp -p $$d/$$file $(distdir)/$$file || :; \
 	  fi; \
 	done
+perl.lo perl.o : perl.c ../lib/m4module.h ../lib/m4error.h \
+	../lib/m4obstack.h perlxsi.c
+shadow.lo shadow.o : shadow.c ../lib/m4module.h ../lib/m4error.h \
+	../lib/m4obstack.h
+stdlib.lo stdlib.o : stdlib.c ../src/getopt.h ../lib/m4module.h \
+	../lib/m4error.h ../lib/m4obstack.h
+test.lo test.o : test.c ../lib/m4module.h ../lib/m4error.h \
+	../lib/m4obstack.h
+time.lo time.o : time.c ../config.h ../lib/m4module.h ../lib/m4error.h \
+	../lib/m4obstack.h
 
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info-am:
 info: info-am
 dvi-am:
 dvi: dvi-am
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
 installcheck-am:
 installcheck: installcheck-am
@@ -358,25 +401,33 @@ install-pkglibexecLTLIBRARIES mostlyclean-compile distclean-compile \
 clean-compile maintainer-clean-compile mostlyclean-libtool \
 distclean-libtool clean-libtool maintainer-clean-libtool tags \
 mostlyclean-tags distclean-tags clean-tags maintainer-clean-tags \
-distdir info-am info dvi-am dvi check check-am installcheck-am \
-installcheck install-exec-am install-exec install-data-am install-data \
-install-am install uninstall-am uninstall all-redirect all-am all \
-installdirs mostlyclean-generic distclean-generic clean-generic \
-maintainer-clean-generic clean mostlyclean distclean maintainer-clean
+distdir check-TESTS info-am info dvi-am dvi check check-am \
+installcheck-am installcheck install-exec-am install-exec \
+install-data-am install-data install-am install uninstall-am uninstall \
+all-redirect all-am all installdirs mostlyclean-generic \
+distclean-generic clean-generic maintainer-clean-generic clean \
+mostlyclean distclean maintainer-clean
 
+
+# This is experimental - in fact it doesn't work at all
+
+#perl_la_SOURCES = perl.c
+
+#perl_la_CFLAGS = `perl -MExtUtils::Embed -e ccopts`
+#perl_la_LDFLAGS = -module `perl -MExtUtils::Embed -e ldopts`
 
 perlxsi.c:
 	perl -MExtUtils::Embed -e xsinit -- -o perlxsi.c
 
 perl.lo: perl.c perlxsi.c
-	@echo '$(LTCOMPILE) $(libperl_la_CFLAGS) -c perl.c'; \
-	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).p $(libperl_la_CFLAGS) -c perl.c
-	@-sed -e 's/^\([^:]*\)\.o:/\1.lo \1.o:/' \
-	  < .deps/$(*F).p > .deps/$(*F).P
-	@-rm -f .deps/$(*F).p
-
-libperl.la: $(libperl_la_OBJECTS) $(libperl_la_DEPENDENCIES)
-	$(LINK) -rpath $(pkglibexecdir) $(libperl_la_LDFLAGS) $(PERLLDFLAGS) $(libperl_la_OBJECTS) $(libperl_la_LIBADD) $(LIBS)
+	@echo '$(LTCOMPILE) $(perl_la_CFLAGS) -c $<'; \
+	$(LTCOMPILE) -Wp,-MD,.deps/$(*F).pp $(perl_la_CFLAGS) -c $<
+	@-sed -e 's/^\([^:]*\)\.o[ 	]*:/\1.lo \1.o :/' \
+	  < .deps/$(*F).pp > .deps/$(*F).P; \
+	tr ' ' '\012' < .deps/$(*F).pp \
+	  | sed -e 's/^\\$$//' -e '/^$$/ d' -e '/:$$/ d' -e 's/$$/ :/' \
+	    >> .deps/$(*F).P; \
+	rm -f .deps/$(*F).pp
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
