* Makefile.am (AUTOMAKE_OPTIONS): 1.5. Don't use aclocal: it's written by hand. * aclocal.m4: m4_include all the files instead of being built by aclocal. * bootstrap: Help automake find the AC_SUBSTs and AM_CONDITIONALs until it reads the traces by itself. * configure.in: Require Autoconf 2.42c as we are now using AC_CONFIG_TESTDIR instead of AT_CONFIG. Catch unexpanded `jm_' macros. * config/atconfig.m4: Remove. * config/error.m4: new. * config/Makefile.am: Ship the files included by aclocal.m4. * tests/Makefile.am (TESTSUITE_SOURCES): Rename as... (TESTSUITE_AT): this, to please Automake. (TESTSUITE): This target uses autotest/autotest.m4, not autotest/general.m4. * tests/testsuite.at: Prereq Autotest 2.52c. * examples/Makefile.am (pkgdata_DATA): Rename as... (dist_pkgdata_DATA): this. * doc/Makefile.am (man_MANS): Rename as... (dist_man_mans): this.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -7,7 +7,26 @@ auxdir=`grep '^AC_CONFIG_AUX_DIR' configure.in | sed 's/^.*(\([^)]*\)).*$/\1/'`
 
 rm -f config.cache
 
-aclocal -I ./$auxdir  || exit 1
+# Make a copy of each Automake/Gettext m4 file we need.
+aclocal_libdir=`aclocal --print-ac-dir`
+for i in `make -f config/Makefile.am list-standard-macros`
+do
+  cp $aclocal_libdir/$i config ||
+    echo "$0: cannot find $i" >&2
+done
+
+# Automake understands nothing to our aclocal and misses all its
+# AC_SUBST...
+(
+  set -e
+  sed -n '1,/# Help Automake understand includes./p' aclocal.m4
+  echo "# It doesn't see AC_SUBSTs."
+  autoconf -t AC_SUBST:'AC_SUBST([$1])' | sort -u
+  echo "# It doesn't see AM_CONDITIONALs."
+  autoconf -t AM_CONDITIONAL:'AM_CONDITIONAL([$1])' | sort -u
+) >aclocal.m4t
+mv aclocal.m4t aclocal.m4
+
 # shtoolize -q -I ./$auxdir echo move install mkdir version || exit 1
 # libtoolize -f -c || exit 1
 # gettextize -f -c  || exit 1
