Import of m4-1.4k

diff --git a/examples/Makefile.in b/examples/Makefile.in
--- a/examples/Makefile.in
+++ b/examples/Makefile.in
@@ -88,16 +88,58 @@ USE_NLS = @USE_NLS@
 VERSION = @VERSION@
 l = @l@
 
-EXTRA_DIST = $(pkgdata_DATA)
+EXTRA_DIST = $(pkgdata_DATA) $(TESTS) defs mktests.sh
 
-pkgdata_DATA = capitalize.m4 comments.m4 ddivert.m4 debug.m4 esyscmd.m4 \
-	exp.m4 file.m4 foreach.m4 forloop.m4 fstab.m4 hanoi.m4 incl-test.m4 \
-	include.m4 indir.m4 misc.m4 multiquotes.m4 patsubst.m4 pushpop.m4 \
-	regexp.m4 reverse.m4 stackovf.sh sync-lines.m4 sysv-args.m4 trace.m4 \
-	translit.m4 undivert.incl undivert.m4 wrap.m4 iso8859.m4 \
-	\
-	comments.test ddivert.test debug.test iso8859.test \
-	reverse.test sysv-args.test wrap.test
+pkgdata_DATA = \
+	capitalize.m4 \
+	comments.m4 \
+	ddivert.m4 \
+	debug.m4 \
+	esyscmd.m4 \
+	exp.m4 \
+	foreach.m4 \
+	forloop.m4 \
+	fstab.m4 \
+	hanoi.m4 \
+	incl-test.m4 \
+	include.m4 \
+	indir.m4 \
+	misc.m4 \
+	multiquotes.m4 \
+	patsubst.m4 \
+	pushpop.m4 \
+	regexp.m4 \
+	reverse.m4 \
+	sysv-args.m4 \
+	trace.m4 \
+	translit.m4 \
+	undivert.incl \
+	undivert.m4 \
+	wrap.m4
+
+TESTS =	capitalize.test \
+	comments.test \
+	ddivert.test \
+	debug.test \
+	esyscmd.test \
+	exp.test \
+	foreach.test \
+	forloop.test \
+	fstab.test \
+	hanoi.test \
+	include.test \
+	indir.test \
+	misc.test \
+	multiquotes.test \
+	patsubst.test \
+	pushpop.test \
+	regexp.test \
+	reverse.test \
+	sysv-args.test \
+	trace.test \
+	translit.test \
+	undivert.test \
+	wrap.test
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
 CONFIG_HEADER = ../config.h
 CONFIG_CLEAN_FILES = 
@@ -154,9 +196,35 @@ distdir: $(DISTFILES)
 	  || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
 	  || cp -p $$d/$$file $(distdir)/$$file; \
 	done
+check-TESTS: $(TESTS)
+	@failed=0; all=0; \
+	srcdir=$(srcdir); export srcdir; \
+	for tst in $(TESTS); do \
+	  if test -f $$tst; then dir=.; \
+	  else dir="$(srcdir)"; fi; \
+	  if $(TESTS_ENVIRONMENT) $$dir/$$tst; then \
+	    all=`expr $$all + 1`; \
+	    echo "PASS: $$tst"; \
+	  elif test $$? -ne 77; then \
+	    all=`expr $$all + 1`; \
+	    failed=`expr $$failed + 1`; \
+	    echo "FAIL: $$tst"; \
+	  fi; \
+	done; \
+	if test "$$failed" -eq 0; then \
+	  banner="All $$all tests passed"; \
+	else \
+	  banner="$$failed of $$all tests failed"; \
+	fi; \
+	dashes=`echo "$$banner" | sed s/./=/g`; \
+	echo "$$dashes"; \
+	echo "$$banner"; \
+	echo "$$dashes"; \
+	test "$$failed" -eq 0
 info:
 dvi:
 check: all
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 installcheck:
 install-exec: 
 	@$(NORMAL_INSTALL)
@@ -195,13 +263,18 @@ maintainer-clean:  maintainer-clean-generic distclean
 	@echo "This command is intended for maintainers to use;"
 	@echo "it deletes files that may require special tools to rebuild."
 
-.PHONY: uninstall-pkgdataDATA install-pkgdataDATA tags distdir info dvi \
-installcheck install-exec install-data install uninstall all \
-installdirs mostlyclean-generic distclean-generic clean-generic \
-maintainer-clean-generic clean mostlyclean distclean maintainer-clean
+.PHONY: uninstall-pkgdataDATA install-pkgdataDATA tags distdir \
+check-TESTS info dvi installcheck install-exec install-data install \
+uninstall all installdirs mostlyclean-generic distclean-generic \
+clean-generic maintainer-clean-generic clean mostlyclean distclean \
+maintainer-clean
 
 
 all:
+
+defs: $(top_srcdir)/tests/defs
+	cp $(top_srcdir)/tests/defs $@
+	chmod 444 $@
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
